name: build image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'app/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Start
        run: echo "Beginning to build steps"
      
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      # - name: Test AWS CLI
      #   run: aws sts get-caller-identity

      - name: Configure AWS CLI
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 255945442255.dkr.ecr.us-east-1.amazonaws.com

      - uses: docker-practice/actions-setup-docker@master
      
      - name: Build the Image
        working-directory: app
        run: docker build -t justinlim-ce-terraform-game2048-ecr .

      - name: Tag the Image As The Latest
        working-directory: app
        run: docker justinlim-ce-terraform-game2048-ecr:latest 255945442255.dkr.ecr.us-east-1.amazonaws.com/justinlim-ce-terraform-game2048-ecr:latest

      - name: Push the Image to ECR
        run: docker push 255945442255.dkr.ecr.us-east-1.amazonaws.com/justinlim-ce-terraform-game2048-ecr:latest