name: build image

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'infrastructure/**'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Start
        run: echo "Beginning to build steps"
      
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      # - name: Test AWS CLI
      #   run: aws sts get-caller-identity

      # - name: Build Docker Image
      #   uses: 