name: build infrastructure

on:
  push:
    branches:
      - 'main'
    paths:
      - 'infrastructure/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
      
      - name: Go Into Infrastructure Folder
        run: cd infra/

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Validate
        run: terraform validate -no-color
    
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
    
      - name: Terraform Apply
        run: terraform apply --auto-approve